-- db_structure.sql
-- Student Event Management - Database schema
-- Use with: mysql -u root -p < project/db/db_structure.sql

-- 1. Drop & create database
DROP DATABASE IF EXISTS student_events_db;
CREATE DATABASE student_events_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE student_events_db;

-- 2. Users table
-- Stores both normal students and admin accounts
CREATE TABLE users (
    user_id     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        ENUM('student','admin') NOT NULL DEFAULT 'student',
    student_id  VARCHAR(50) NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 3. Events table
-- Created/managed by admin; students can view & register
CREATE TABLE events (
    event_id      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    date          DATE NOT NULL,
    time          TIME NULL,
    venue         VARCHAR(255) NOT NULL,
    organizer     VARCHAR(255) DEFAULT NULL,
    description   TEXT,
    image_path    VARCHAR(255) DEFAULT NULL,
    created_by    INT UNSIGNED NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_events_created_by
      FOREIGN KEY (created_by) REFERENCES users(user_id)
      ON DELETE SET NULL
) ENGINE=InnoDB;

-- 4. Registrations table
-- Tracks which user registered for which event
CREATE TABLE registrations (
    reg_id        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id       INT UNSIGNED NOT NULL,
    event_id      INT UNSIGNED NOT NULL,
    student_id    VARCHAR(50) NULL,
    contact_no    VARCHAR(50) NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reg_user
      FOREIGN KEY (user_id) REFERENCES users(user_id)
      ON DELETE CASCADE,
    CONSTRAINT fk_reg_event
      FOREIGN KEY (event_id) REFERENCES events(event_id)
      ON DELETE CASCADE,

    CONSTRAINT uniq_user_event UNIQUE (user_id, event_id)
) ENGINE=InnoDB;

-- 5. Seed admin user
-- IMPORTANT:
-- Replace the password hash with one generated by:
-- php -r "echo password_hash('Admin123', PASSWORD_DEFAULT) . PHP_EOL;"
-- and re-run this file, OR update row manually.

INSERT INTO users (name, email, password, role)
VALUES (
  'Administrator',
  'admin@example.com',
  '$2y$10$replace_this_with_real_bcrypt_hash______________',
  'admin'
);

-- 6. Sample events (optional demo data)
INSERT INTO events (title, date, time, venue, organizer, description)
VALUES
('AI Seminar 2025',
 '2025-12-10', '10:00:00',
 'Dept. of IT Auditorium',
 'Dept. of IT',
 'Introduction to AI, LLMs and modern student projects.'),

('Hackathon 2025',
 '2025-12-15', '09:00:00',
 'Main Hall',
 'CS Society',
 '24-hour coding challenge for student teams with prizes.');

